import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/Navbar";
import { AuthProvider } from "../context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen from-sky-50 via-white to-sky-100 text-slate-800">
        {/* ✅ Navbar now loads on all pages */}
        <AuthProvider>
        <Navbar />

        {/* Padding to avoid content hiding behind the fixed navbar */}
        <main className="">{children}</main>

        {/* Toast notifications */}
        <Toaster richColors position="top-center" />
        </AuthProvider>
      </body>
    </html>
  );
}
